---
- name: install nginx
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: present
  - name: service start
    service:
      name: nginx
      state: started

